### PR TITLE
some updates to the tohoku example

### PR DESCRIPTION
**Pull request by rjleveque**
@donnaaboise:  I'm not sure why the new version gives bigger v-velocity peaks than the original plots in the paper when it is run with 6 levels, I will try to investigate some more.

I rearranged the notebook a bit and changed it to also download the zenodo data repository if it's not already present.   And I improved some of the plots generated by setplot, IMHO, let me know what you think.

When I tried making kml files I got errors like what's below that I haven't yet tracked down.

```
KML ===> Creating file Tohoku_2011.kml
Traceback (most recent call last):
  File "/Users/rjl/git/clawpack/visclaw/src/python/visclaw/plotclaw.py", line 166, in <module>
    plotclaw(sys.argv[1], sys.argv[2], sys.argv[3])
  File "/Users/rjl/git/clawpack/visclaw/src/python/visclaw/plotclaw.py", line 141, in plotclaw
    plotpages.plotclaw_driver(plotdata, verbose=False, format=format)
  File "/Users/rjl/git/clawpack/visclaw/src/python/visclaw/plotpages.py", line 2760, in wrapper
    return f(*args, **kwds)
  File "/Users/rjl/git/clawpack/visclaw/src/python/visclaw/plotpages.py", line 3041, in plotclaw_driver
    plotpages.plotclaw2kml(plotdata)
  File "/Users/rjl/git/clawpack/visclaw/src/python/visclaw/plotpages.py", line 1706, in plotclaw2kml
    deepcopy(initial_view),
UnboundLocalError: local variable 'initial_view' referenced before assignment
make: *** [plots] Error 1
```

### CODE REVIEW

**Comment by donnaaboise** [comment]
I re-ran the code from the new repo, and it all looks good.  Not sure what to say about the spikes in the v-velocities, though.   

The error in plotting has an easy fix :  set `plotfigure.show = False` for the KML figure.

**Comment by rjleveque** [comment]
@donnaaboise: Thanks!  I can set `plotfigure.show = False` for the kml figure but then of course it doesn't make kml figures, so we might as well remove this altogether from `setplot.py`?    The fact that's it in there made me think it is supposed to work.

The error arises when trying to make plots based on `plotdata.kml_publish` being set to something other than `None`.  This is set to a boisestate webpage so presumably this doesn't work anyway.  When I comment that out, it runs and creates `_plots/Tohoku_2011.kmz` but the images don't show up. 

I'll debug all this later, but for now will remove all the kml stuff from setplot since it doesn't seem needed for this example anyway.

**Comment by donnaaboise** [comment]
The KML stuff should all work - it works for me!     But I'll look through it again.

**Comment by donnaaboise** [comment]
I could also create a separate file just for KML plotting.

**Comment by donnaaboise** [comment]
I am not sure what you mean when you say the images don't show up.   They can take a while to load in Google Earth.  Did you try turning on the animation?  

The publish setting is for creating a webpage that contains the  link to the KMZ file.  The setting can be removed.

**Comment by donnaaboise** [comment]
I see at least one issue :  If `plot figure.show = True`, but `plotdata.fignos` does not contain Frame 4,  the plotting crashes.  I looks like I have to re-think the logic there.   I can't completely remember what I did.    But maybe the best thing is to just have a separate file for plotting KML, with everything set so that a KML file will be produced.

**Comment by rjleveque** [comment]
Yes, it might be best to have a separate `setplot_kml.py` file as we do in chile2010 for making the kml plots.

I'm working on the notebook a bit more and adding some figures from the original paper for comparison, will push soon.

**Comment by donnaaboise** [comment]
Okay - I'll go ahead and make a separate setplot file.

**Comment by rjleveque** [comment]
I'm going to merge this for now so I can add `tsunami-examples` to the `apps` repository as a submodule.  We can work more on kml files and other possible improvements later.

**Pull request merged**
